---


- name: PLAY 01 --- GATHER PROPERTIES ON DEVICES
  hosts: ADM-IOSdevices JIA-IOSdevices
  connection: network_cli
  # serial: 1
  gather_facts: no

  # vars:
  #   pattern: aaa new-model
  tasks:

    - name: PLAY 01 --- GET FACTS FROM DEVICE
      ios_facts:
        # provider:
          # username: stison-admin
          # password: glitchyInTh3@ir
      ignore_errors: yes 
      register: results
          

    - name: GET DEVICE DATA FOR DATA-BASE AND SAVE TO FILE
      lineinfile:
        line: "{{ ansible_net_hostname }}   {{ ansible_net_neighbors }}  {{ ansible_net_all_ipv4_addresses }}"
        path: "{{ playbook_dir }}/{{ ansible_net_hostname }}dataForNetDevInvenNeighbour"
        create: yes
      # with_items: "{{ ansible_net_model | dict2items }}"
      # when: item.value.operstatus == 'down'
    # - debug:
    #      var: ansible_net_model